### ISSUE TITLE
Can't connect  to FCM or register with Expo

### ISSUE THREAD

**Issue by s8wa2** [liamcottle/atlas-for-rust#5]
Can't seem to get atlas working anymore. Was working a week or so back, now has issues. FCM and Expo statuses remain constant and don't seem to work. Does not fix itself after logging out / in again. 

Problem still persists even after
- Updating to 1.0.3 and manually clearing saved data.
- Testing multiple separate steam account
- Testing on different devices

See attached images. 

![image](https://user-images.githubusercontent.com/86946027/135558034-8d17caff-1b2a-4c56-b94a-660cda10d51f.png)

**Comment by liamcottle** [comment]
Thanks for the report.

I've just investigated this, and it turns out it's not an issue with FCM at all. I had a bug in Atlas where an Expo error was passed back to the FCM error handler. This has been fixed in master. So it will correctly show this as an Expo Status error and not an FCM Status error.

Moving back to the actual issue... The Expo certificate (for https://exp.host) is being marked as expired. After looking into this, it's not actually expired, but one of the Root CA certs for Let's Encrypt has expired. More info on that here: [DST Root CA X3](https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021)

This isn't an issue for the latest browsers etc, but Atlas uses Electron and it appears there's a missing config for how it verifies the full chain of certificates https://github.com/electron/electron/issues/31212 and a fix has been merged into Electron here https://github.com/electron/electron/pull/31213

Unfortunately Atlas is using Electron v11 and according to [this comment](https://github.com/electron/electron/pull/31213#issuecomment-931587075) the fix is only going to be backported to Electron v12+.

Ideally, we would upgrade to Electron v15/v16 but I don't have too much time for this at the moment.

For now, I am going to disable SSL certificate verification for the api call to register for an Expo Token and then I'll push out a new version.

**Comment by liamcottle** [comment]
Fixed in [v1.0.4](https://github.com/liamcottle/atlas-for-rust/releases/tag/v1.0.4)
